arch = [
    "cameractrls",
    "conky",
    "firefox",
    "gucharmap",
    "maim",
    "openbox",
    "picom",
    "redshift",
    "rofi",
    "rofi-calc",
    "rofi-emoji",
    "satty",
    "seahorse",
    "simplescreenrecorder",
    "syncthing",
    "thunar",
    "tint2",
    "typora",
    "viewnior",
    "xdotool",
    "xfce4-notifyd",
    "xorg-server",
    "xorg-xev",
    "xorg-xinit",
    "xorg-xrandr",
    "xorg-xset",
    "zathura",
    "zathura-pdf-mupdf",
    "zen-browser-bin",
]
